#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.
obj-y  += hynitron_ts.o
#hynitron_ts-objs += hynitron.o hynitron_ctl.o hynitron_ex_fun.o
hynitron_ts-objs := hynitron.o
hynitron_ts-objs += hynitron_ctl.o
hynitron_ts-objs += hynitron_ex_fun.o
#hynitron_ts-y    += hynitron.o hynitron_ctl.o hynitron_ex_fun.o
# hynitron_ts-objs +=  ft_gesture_lib.a
# $(obj)/ft_gesture_lib.a: $(srctree)/$(obj)/ft_gesture_lib
#	cp $(srctree)/$(obj)/ft_gesture_lib $(obj)/ft_gesture_lib.a
